### PR TITLE
utils scripts enhancements

### PR DESCRIPTION
**Pull request by bgorbuntsov**
Adapted certificate generation files to use Amazon profiles.
Added the verbose parameter to disable output of full generated payload.
Fixed output descriptions of generated files for better understanding of their contents.

As the script files for client and server certificates generation are roughly the same, a new universal script has been added that can accept the "--server" argument to generate a server certificate, otherwise it will generate the user certificate.
This new script can also take variables for certificate generation from the file, so you can use the '--vardir' and '--varfile' arguments to specify the directory and file containing the variables.
The '--destination' argument can be used to specify the destination directory for generated files.
The '--keyalgo' argument can be used to override the key specs.
The '--keygenalias' argument can be used to override the corresponding variable from the variable file. If not specified, the 'key_alias' argument from the file will be used.

If the arguments are omitted, the script will use the 'utils/variables' directory and the 'client.json' file as the variable file. The default destination directory path is "~/ca/certificates".

### CODE REVIEW

**Comment by paulschwarzenberger** [comment]
Looks good, I've done some initial testing. Previously with the client cert script I could run this against the default CA environment, and it would issue a certificate without having to enter any details or change anything.

Following your update, I get an error that it can't find the key ID.
This was testing without using a profile, simply copying the standard AWS variables and values, and pasting into the command line.
```
export AWS_ACCESS_KEY_ID="xxxxxxxx"
export AWS_SECRET_ACCESS_KEY="yyyyyyyy"
export AWS_DEFAULT_REGION=eu-west-2
```

**Comment by paulschwarzenberger** [comment]
If I do the equivalent test using the same credentials configured as a profile, it works

**Comment by bgorbuntsov** [comment]
Thanks! I pushed the fix. Please check again.

**Comment by paulschwarzenberger** [comment]
The script works now both with and without the profile argument.
On line 197 of generate-cert.py you say:
```
print(f"Intermediate CA pem bundle written to {output_path_cert_pem}")
```
As this is a PEM file containing the client cert, issung (intermediate) CA and root CA, I think it would be better to call it a certificate chain:
```
print(f"Certificate chain written to {output_path_cert_pem}")
```

**Review by paulschwarzenberger — APPROVED** [review]
Tested on both MacOS and Windows
LGTM

**Pull request merged**
